# Generated by Django 4.2.11 on 2025-03-11 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0003_task_tasker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolistapp.taskers'),
        ),
    ]
